version: '3.5' 

services: 

    backend: 
      image: kaldmanf/backend-2_3
      environment: 
        - REQUEST_ORIGIN=http://localhost:5000
        - PORT=8080
        - REDIS_HOST=redis
        - POSTGRES_HOST=db
      command: ./server
      depends_on:
        - db
      container_name: backend-2_3

    frontend: 
      image: kaldmanf/frontend-2_3
      depends_on:
        - backend
      environment: 
        - REACT_APP_BACKEND_URL=http://localhost:8080
      container_name: frontend-2_3
    
    redis:
      image: redis

    db:
      image: postgres
      restart: always
      environment:
        POSTGRES_PASSWORD: postgres

    nginx:
      image: kaldmanf/nginx
      build: ./nginx
      ports: 
        - 80:80
      depends_on:
        - backend
        - frontend
      volumes:
        - ./nginx/nginx.conf:/etc/nginx/nginx.conf


    