version: '3.5' 

services: 

    simple-web-service: 
      image: kaldmanf/simple-web-service
      build: . 
      volumes: 
        - ./text.log:/usr/src/app/text.log
      container_name: simple-web-service